In [2]:
import pandas as pd

In [3]:
train_data=pd.read_csv("../data/raw/train.csv")

In [5]:
train_data.head()

          seq  label  edit_distance class cluster_centre
0  FFVSGFYYQA      0              7   mid     LMVSGLYYQA
1  LCVSGFYSQA      0              7   mid     LMVSGLYYQA
2  FMVSGLYYQD      0              7   mid     LMVSGLYYQA
3  LIVSGLYYKA      0              8   mid     LMVSGLYYQA
4  LMVSGFYFYA      0              7   mid     LMVSGLYYQA

In [6]:
train_data.shape

(367044, 5)

In [7]:
train_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 367044 entries, 0 to 367043
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   seq             367044 non-null  str
 1   label           367044 non-null  int64
 2   edit_distance   367044 non-null  int64
 3   class           367044 non-null  str
 4   cluster_centre  367044 non-null  str
dtypes: int64(2), str(3)
memory usage: 14.0 MB

In [9]:
train_data['class'].value_counts()

class
mid     143278
high    120505
low     103261
Name: count, dtype: int64

In [10]:
train_data['label'].value_counts()

label
0    246539
1    120505
Name: count, dtype: int64

In [11]:
train_data['cluster_centre'].value_counts()

cluster_centre
WGLSGLYVYS    11623
WATLGMYVFV     3965
WSQDSIYVFA     3432
WLLSGFYVFA     3338
WTHAGMYMFS     2918
              ...
GTARLLPTPL        1
YSLLGNGVAF        1
MELQAHTSSP        1
GSSKLNKLCI        1
LNEFGLWHVH        1
Name: count, Length: 13829, dtype: int64

In [13]:
pd.crosstab(train_data["class"], train_data["label"])

label       0       1
class
high        0  120505
low    103261       0
mid    143278       0

In [4]:
val_data=pd.read_csv("../data/raw/val.csv")
test_data=pd.read_csv("../data/raw/test.csv")

In [15]:
print("Train:", train_data.shape)
print("Val:", val_data.shape)
print("Test:", test_data.shape)

Train: (367044, 5)
Val: (78651, 5)
Test: (78651, 5)

In [17]:
train_data[["seq","cluster_centre"]].head(10)

          seq cluster_centre
0  FFVSGFYYQA     LMVSGLYYQA
1  LCVSGFYSQA     LMVSGLYYQA
2  FMVSGLYYQD     LMVSGLYYQA
3  LIVSGLYYKA     LMVSGLYYQA
4  LMVSGFYFYA     LMVSGLYYQA
5  LIVSGLYYKD     LMVSGLYYQA
6  LLVSGSYYYA     LMVSGLYYQA
7  LIVSGLYYQA     LMVSGLYYQA
8  LMVSGLYYQA     LMVSGLYYQA
9  LMVSGLYFQA     LMVSGLYYQA

In [34]:
train_data["cluster_centre"].nunique()

13829

In [35]:
test_data["cluster_centre"].nunique()

706

In [37]:
val_data["cluster_centre"].nunique()

251

In [19]:
train_clusters = set(train_data["cluster_centre"])
val_clusters = set(val_data["cluster_centre"])
test_clusters = set(test_data["cluster_centre"])

In [20]:
print("Train-Val overlap:", len(train_clusters & val_clusters))
print("Train-Test overlap:", len(train_clusters & test_clusters))
print("Val-Test overlap:", len(val_clusters & test_clusters))

Train-Val overlap: 0
Train-Test overlap: 0
Val-Test overlap: 0

In [22]:
train_data["seq"].str.len().value_counts().sort_index()

seq
10    367044
Name: count, dtype: int64

In [23]:
train_data["seq"].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
367039    False
367040    False
367041    False
367042    False
367043    False
Name: seq, Length: 367044, dtype: bool

In [24]:
train_data["seq"].duplicated().sum()

np.int64(0)

In [25]:
print("Train duplicates:", train_data["seq"].duplicated().sum())
print("Val duplicates:", val_data["seq"].duplicated().sum())
print("Test duplicates:", test_data["seq"].duplicated().sum())

Train duplicates: 0
Val duplicates: 0
Test duplicates: 0

In [26]:
train_seqs = set(train_data["seq"])
val_seqs = set(val_data["seq"])
test_seqs = set(test_data["seq"])

print("Train-Val sequence overlap:", len(train_seqs & val_seqs))
print("Train-Test sequence overlap:", len(train_seqs & test_seqs))
print("Val-Test sequence overlap:", len(val_seqs & test_seqs))

Train-Val sequence overlap: 0
Train-Test sequence overlap: 0
Val-Test sequence overlap: 0

In [28]:
print("Train:\n", train_data["class"].value_counts(normalize=True))
print("Validation:\n", val_data["class"].value_counts(normalize=True))
print("Test:\n", test_data["class"].value_counts(normalize=True))

Train:
 class
mid     0.390356
high    0.328312
low     0.281331
Name: proportion, dtype: float64
Validation:
 class
low     0.434832
high    0.328311
mid     0.236856
Name: proportion, dtype: float64
Test:
 class
mid     0.357325
high    0.328311
low     0.314363
Name: proportion, dtype: float64

In [29]:
print("Train:\n", train_data["label"].value_counts(normalize=True))
print("Validation:\n", val_data["label"].value_counts(normalize=True))
print("Test:\n", test_data["label"].value_counts(normalize=True))

Train:
 label
0    0.671688
1    0.328312
Name: proportion, dtype: float64
Validation:
 label
0    0.671689
1    0.328311
Name: proportion, dtype: float64
Test:
 label
0    0.671689
1    0.328311
Name: proportion, dtype: float64

In [30]:
print("Train:\n", train_data.isna().sum())
print("\nValidation:\n", val_data.isna().sum())
print("\nTest:\n", test_data.isna().sum())

Train:
 seq               0
label             0
edit_distance     0
class             0
cluster_centre    0
dtype: int64

Validation:
 seq               0
label             0
edit_distance     0
class             0
cluster_centre    0
dtype: int64

Test:
 seq               0
label             0
edit_distance     0
class             0
cluster_centre    0
dtype: int64

In [31]:
train_data.isna()

          seq  label  edit_distance  class  cluster_centre
0       False  False          False  False           False
1       False  False          False  False           False
2       False  False          False  False           False
3       False  False          False  False           False
4       False  False          False  False           False
...       ...    ...            ...    ...             ...
367039  False  False          False  False           False
367040  False  False          False  False           False
367041  False  False          False  False           False
367042  False  False          False  False           False
367043  False  False          False  False           False

[367044 rows x 5 columns]

In [32]:
train_data.isna().sum()

seq               0
label             0
edit_distance     0
class             0
cluster_centre    0
dtype: int64

In [43]:
print(
    "Train:\n",
    train_data["edit_distance"].value_counts(normalize=True).sort_index()
)

print(
    "Validation:\n",
    val_data["edit_distance"].value_counts(normalize=True).sort_index()
)

print(
    "Test:\n",
    test_data["edit_distance"].value_counts(normalize=True).sort_index()
)

Train:
 edit_distance
2     0.000616
3     0.001624
4     0.008124
5     0.047019
6     0.161812
7     0.314919
8     0.292578
9     0.134586
10    0.038723
Name: proportion, dtype: float64
Validation:
 edit_distance
1     0.000636
2     0.004361
3     0.009536
4     0.026306
5     0.049828
6     0.139769
7     0.284637
8     0.320072
9     0.150882
10    0.013973
Name: proportion, dtype: float64
Test:
 edit_distance
2     0.000394
3     0.001831
4     0.017050
5     0.093235
6     0.204104
7     0.281649
8     0.232356
9     0.113095
10    0.056287
Name: proportion, dtype: float64

In [44]:
print(
    "Test:\n",
    test_data["edit_distance"].value_counts(normalize=True).sort_index()
)

Test:
 edit_distance
2     0.000394
3     0.001831
4     0.017050
5     0.093235
6     0.204104
7     0.281649
8     0.232356
9     0.113095
10    0.056287
Name: proportion, dtype: float64

In [1]:
from pathlib import Path
from her2clf.data import load_splits

In [2]:
data_dir=Path("../data/raw")
train_data, val_data, test_data=load_splits(data_dir)

In [4]:
print(train_data.shape, val_data.shape, test_data.shape)

(367044, 5) (78651, 5) (78651, 5)

In [5]:
seq=train_data["seq"][0]

In [6]:
seq

'FFVSGFYYQA'

In [7]:
list(seq)

['F', 'F', 'V', 'S', 'G', 'F', 'Y', 'Y', 'Q', 'A']

In [8]:
train_data["seq"].apply(list)

0         [F, F, V, S, G, F, Y, Y, Q, A]
1         [L, C, V, S, G, F, Y, S, Q, A]
2         [F, M, V, S, G, L, Y, Y, Q, D]
3         [L, I, V, S, G, L, Y, Y, K, A]
4         [L, M, V, S, G, F, Y, F, Y, A]
                       ...
367039    [G, T, A, R, L, L, P, T, P, L]
367040    [Y, S, L, L, G, N, G, V, A, F]
367041    [M, E, L, Q, A, H, T, S, S, P]
367042    [G, S, S, K, L, N, K, L, C, I]
367043    [L, N, E, F, G, L, W, H, V, H]
Name: seq, Length: 367044, dtype: object

In [9]:
train_seq = train_data["seq"].apply(list).tolist()

In [13]:
len(train_seq)

367044

In [11]:
len(train_seq[0])

10

In [12]:
train_seq[0]

['F', 'F', 'V', 'S', 'G', 'F', 'Y', 'Y', 'Q', 'A']

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
encoder=OneHotEncoder(handle_unknown="ignore")
X_train=encoder.fit_transform(train_seq)

In [39]:
import pandas as pd

X_preview = pd.DataFrame(
    X_train[:5].toarray(),
    columns=encoder.get_feature_names_out()
)

X_preview

,x0_A,x0_C,x0_D,x0_E,x0_F,x0_G,x0_H,x0_I,x0_K,x0_L,...,x9_M,x9_N,x9_P,x9_Q,x9_R,x9_S,x9_T,x9_V,x9_W,x9_Y
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
X_train.shape

(367044, 200)

In [18]:
train_data["seq"].head(10)

0    FFVSGFYYQA
1    LCVSGFYSQA
2    FMVSGLYYQD
3    LIVSGLYYKA
4    LMVSGFYFYA
5    LIVSGLYYKD
6    LLVSGSYYYA
7    LIVSGLYYQA
8    LMVSGLYYQA
9    LMVSGLYFQA
Name: seq, dtype: str

In [20]:
type(train_data["seq"])

pandas.Series

In [21]:
val_seq = val_data["seq"].apply(list).tolist()

In [22]:
test_seq = test_data["seq"].apply(list).tolist()

In [23]:
X_val=encoder.transform(val_seq)

In [24]:
X_test=encoder.transform(test_seq)

In [25]:
X_val.shape

(78651, 200)

In [26]:
X_test.shape

(78651, 200)

In [27]:
y_train = train_data["label"]
y_val = val_data["label"]
y_test = test_data["label"]

In [28]:
X_train.shape, y_train.shape

((367044, 200), (367044,))

In [29]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [40]:
val_prob=model.predict_proba(X_val)[:,1]

In [31]:
from sklearn.metrics import roc_auc_score, average_precision_score

roc_auc = roc_auc_score(y_val, val_prob)
pr_auc = average_precision_score(y_val, val_prob)

print("ROC-AUC:", roc_auc)
print("PR-AUC:", pr_auc)

ROC-AUC: 0.9643616850123388
PR-AUC: 0.9364805889406737

### Baseline: One-hot + Logistic Regression

Representation: position-specific one-hot encoding (200 features)
Model: Logistic Regression
Split: clonotype split

Validation:
- ROC-AUC: 0.9644
- PR-AUC: 0.9365

In [41]:
val_results=val_data[["seq", "label", "edit_distance"]].copy()
val_results["prob"]=val_prob
val_results.head()

          seq  label  edit_distance      prob
0  WYALPFYKYD      1              6  0.853679
1  WYAQPFYYYD      1              6  0.830298
2  WYAQAFYYYD      1              6  0.734318
3  WNAQAFYIYD      1              6  0.366453
4  GALLAATLRL      0             10  0.521642

In [44]:
val_results["edit_distance"].value_counts().sort_index()

edit_distance
1        50
2       343
3       750
4      2069
5      3919
6     10993
7     22387
8     25174
9     11867
10     1099
Name: count, dtype: int64

In [47]:
from sklearn.metrics import roc_auc_score, average_precision_score

results_by_distance = []

for distance, group in val_results.groupby("edit_distance"):
    roc_auc = roc_auc_score(group["label"], group["prob"])
    pr_auc = average_precision_score(group["label"], group["prob"])

    results_by_distance.append({
        "edit_distance": distance,
        "n": len(group),
        "roc_auc": roc_auc,
        "pr_auc": pr_auc
    })

results_by_distance = pd.DataFrame(results_by_distance)
results_by_distance

   edit_distance      n   roc_auc    pr_auc
0              1     50  0.593750  0.979641
1              2    343  0.602683  0.981791
2              3    750  0.720351  0.961597
3              4   2069  0.740550  0.924762
4              5   3919  0.787574  0.871121
5              6  10993  0.872994  0.858768
6              7  22387  0.954570  0.940434
7              8  25174  0.989073  0.978015
8              9  11867  0.988927  0.963728
9             10   1099  0.472659  0.093916

In [48]:
val_results.groupby("edit_distance")["label"].agg(
    n="count",
    positives="sum",
    positive_rate="mean"
)

                   n  positives  positive_rate
edit_distance
1                 50         48       0.960000
2                343        332       0.967930
3                750        683       0.910667
4               2069       1705       0.824070
5               3919       2468       0.629752
6              10993       4573       0.415992
7              22387       8376       0.374146
8              25174       6686       0.265591
9              11867        938       0.079043
10              1099         13       0.011829

### Performance by edit distance

High-affinity prevalence decreases strongly with distance from parental trastuzumab
(~96% at distance 1 to ~1.2% at distance 10).

Because positive prevalence varies substantially across edit-distance groups, PR-AUC
should be interpreted relative to each group's positive rate. The one-hot logistic
regression performs particularly strongly at distances 7–9, while performance at
distance 10 is poor/uncertain and based on only 13 positive examples.

Edit distance is not provided to the model, but is inherently encoded by the sequence.
A later baseline using edit distance alone will test how much predictive signal can be
explained simply by distance from the parent sequence.

In [49]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_val, val_prob)

In [50]:
precision.shape, recall.shape, thresholds.shape

((78652,), (78652,), (78651,))

In [51]:
from sklearn.metrics import precision_score, recall_score, f1_score

for threshold in [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]:
    pred = (val_prob >= threshold).astype(int)

    print(
        threshold,
        "Precision:", round(precision_score(y_val, pred), 3),
        "Recall:", round(recall_score(y_val, pred), 3),
        "F1:", round(f1_score(y_val, pred), 3)
    )

0.2 Precision: 0.603 Recall: 0.983 F1: 0.748
0.3 Precision: 0.689 Recall: 0.963 F1: 0.803
0.4 Precision: 0.76 Recall: 0.935 F1: 0.838
0.5 Precision: 0.82 Recall: 0.895 F1: 0.856
0.6 Precision: 0.872 Recall: 0.842 F1: 0.857
0.7 Precision: 0.916 Recall: 0.768 F1: 0.836
0.8 Precision: 0.953 Recall: 0.652 F1: 0.774

edit-distance only baseline model

In [52]:
X_train_dist = train_data[["edit_distance"]]
X_val_dist = val_data[["edit_distance"]]

In [53]:
distance_model = LogisticRegression()
distance_model.fit(X_train_dist, y_train)

LogisticRegression()

In [54]:
val_prob_dist = distance_model.predict_proba(X_val_dist)[:, 1]

In [55]:
print("ROC-AUC:", roc_auc_score(y_val, val_prob_dist))
print("PR-AUC:", average_precision_score(y_val, val_prob_dist))

ROC-AUC: 0.6992978442308722
PR-AUC: 0.5176465039300809

### Edit-distance-only baseline

To test whether sequence-model performance is primarily explained by distance
from parental trastuzumab, logistic regression was trained using edit distance
as the only feature.

Validation:
- ROC-AUC: 0.6993
- PR-AUC: 0.5176

Edit distance contains substantial predictive signal, but performs far below
the position-specific one-hot sequence baseline (ROC-AUC 0.9644, PR-AUC 0.9365).
Therefore, the sequence model captures information beyond mutation count alone.

In [6]:
from her2clf.features import fit_onehot_encoder, transform_sequences

In [7]:
X_train, encoder=fit_onehot_encoder(train_data["seq"])

In [9]:
X_val= transform_sequences(val_data["seq"], encoder)
X_test= transform_sequences(test_data["seq"], encoder)

In [10]:
X_train.shape, X_val.shape, X_test.shape

((367044, 200), (78651, 200), (78651, 200))